name: Main-Services Infra CD

on:
  push:
    branches: [main]
    paths:
      - infra/services/**

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_oidc_arn: ${{ secrets.AWS_OIDC_PROVIDER_ARN }}

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CD_SERVICES_ROLE }}
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra/services

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra/services