name: Services Frontend CICD

on:
  push:
    branches: [feature-infra]
    paths:
      - services/frontend/**

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_oidc_arn: ${{ secrets.AWS_OIDC_PROVIDER_ARN }}

jobs:
  ci-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        working-directory: services/frontend

      - name: Run Lint
        run: npm run lint
        working-directory: services/frontend

      - name: Run Test
        run: npm run test
        working-directory: services/frontend

      - name: Docker Login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"

      - name: Docker Build Image
        run: docker build -t moorthy265/ecs-microservices:frontend-${{ github.sha }} services/frontend/.

      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: moorthy265/ecs-microservices:frontend-${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Docker Push Image to Docker Hub
        run: docker push moorthy265/ecs-microservices:frontend-${{ github.sha }}
  
  cd-run:
    runs-on: ubuntu-latest
    needs: ci-run

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ secrets.SERVICE_CICD_ROLE }}
          aws-region: ap-south-1

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Register new task definition
        run: |
          TASK_DEF=$(aws ecs describe-task-definition --task-definition ecs_frontend)

          NEW_TASK_DEF=$(echo $TASK_DEF | jq \
            --arg IMAGE "moorthy265/ecs-microservices:frontend-${{ github.sha }}" \
            '.taskDefinition |
             .containerDefinitions[0].image = $IMAGE |
             del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)')

          echo $NEW_TASK_DEF > new-task-def.json

          aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster main \
            --service frontend

